// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szxkvumisnyclqjuicoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6eGt2dW1pc255Y2xxanVpY29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDIwOTcsImV4cCI6MjA2NDM3ODA5N30.ZMvwPibswOlFkfO6lwTlZrT8t-lnlF1QrmHZJJmNKZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);